### ISSUE TITLE
✨ Please consider adding the link popup functionality

### ISSUE THREAD

**Issue by trungng2006** [ebullient/obsidian-slides-extended#15]
### 🔖 Feature description

I would like to be able to open some references while I am presenting.
I think the pop-up (obsidian page preview) would help me in this aspect.

### ✔️ Solution

I want my link to pop up in my note when I hover over the link (with Ctrl pressed down).
Or could you consider letting the functionality of [hover editor](https://github.com/nothingislost/obsidian-hover-editor) to work on slides extended?

**Comment by ebullient** [comment]
The sever used by Slides Extended is treated (basically) as a separate/external server. This is why it has its own port, and why it is available to an external browser. Presentation content is handled by reveal.js outside of any obsidian context, with no access to obsidian functionality.

If you're looking for obsidian-integrated/capable slides, you might look at some newer extensions that present from a canvas layout (using a separate window), rather than something reveal.js-based.

**Comment by trungng2006** [comment]
Thank you for your reponse!!

Then would it be possible if the pop up function still be implement, but for hidden slide?

Ex: I will have 10 slides for the main presentation and 5 slide hidden or put in appendix.
and have a link to those slide. and i can call them (popup) to elaborate if needed.
Do you think this is possible?

**Comment by ebullient** [comment]
Two things:

- keep the slides at the end, and only navigate to them if you need to
- use vertical slides to tuck additional content alongside regular content.. this may be less obvious to use well with the usual "clicker" ... https://revealjs.com/vertical-slides/

**Comment by trungng2006** [comment]
i am aware of vertical slide. but I still think pop up may be a good option to show example.

I do think putting slides at the end and use jump to slide may be a good alternative. Thank you.

Thank you for your consideration!
